package com.tencent.avroom;

public class TXCAVRoomConstants
{
    public static int AVROOM_AUTH_BITS_DEFAULT;
    public static int AVROOM_AUTH_BITS_CREATE_ROOM;
    public static int AVROOM_AUTH_BITS_JOIN_ROOM;
    public static int AVROOM_AUTH_BITS_SEND_AUDIO;
    public static int AVROOM_AUTH_BITS_RECV_AUDIO;
    public static int AVROOM_AUTH_BITS_SEND_CAMERA_VIDEO;
    public static int AVROOM_AUTH_BITS_RECV_CAMERA_VIDEO;
    public static int AVROOM_AUTH_BITS_SEND_SCREEN_VIDEO;
    public static int AVROOM_AUTH_BITS_RECV_SCREEN_VIDEO;
    public static int AVROOM_EVT_REQUEST_IP_SUCC;
    public static int AVROOM_EVT_CONNECT_SUCC;
    public static int AVROOM_EVT_ENTER_ROOM_SUCC;
    public static int AVROOM_EVT_EXIT_ROOM_SUCC;
    public static int AVROOM_EVT_REQUEST_AVSEAT_SUCC;
    public static int AVROOM_ERR_REQUEST_IP_FAIL;
    public static int AVROOM_ERR_CONNECT_FAILE;
    public static int AVROOM_ERR_ENTER_ROOM_FAIL;
    public static int AVROOM_ERR_EXIT_ROOM_FAIL;
    public static int AVROOM_ERR_REQUEST_AVSEAT_FAIL;
    public static int AVROOM_WARNING_DISCONNECT;
    public static int AVROOM_WARNING_RECONNECT;
    public static int AVROOM_WARNING_NET_BUSY;
    public static int AVROOM_EVT_OPEN_CAMERA_SUCC;
    public static int AVROOM_EVT_START_VIDEO_ENCODER;
    public static int AVROOM_EVT_UP_CHANGE_RESOLUTION;
    public static int AVROOM_EVT_UP_CHANGE_BITRATE;
    public static int AVROOM_EVT_FIRST_FRAME_AVAILABLE;
    public static int AVROOM_WARNING_HW_ACCELERATION_ENCODE_FAIL;
    public static int AVROOM_ERR_OPEN_CAMERA_FAIL;
    public static int AVROOM_ERR_OPEN_MIC_FAIL;
    public static int AVROOM_ERR_VIDEO_ENCODE_FAIL;
    public static int AVROOM_ERR_AUDIO_ENCODE_FAIL;
    public static int AVROOM_ERR_UNSUPPORTED_RESOLUTION;
    public static int AVROOM_ERR_UNSUPPORTED_SAMPLERATE;
    public static int AVROOM_EVT_RCV_FIRST_I_FRAME;
    public static int AVROOM_EVT_PLAY_BEGIN;
    public static int AVROOM_EVT_PLAY_LOADING;
    public static int AVROOM_EVT_START_VIDEO_DECODER;
    public static int AVROOM_EVT_DOWN_CHANGE_RESOLUTION;
    public static int AVROOM_WARNING_VIDEO_DECODE_FAIL;
    public static int AVROOM_WARNING_AUDIO_DECODE_FAIL;
    public static int AVROOM_WARNING_HW_ACCELERATION_DECODE_FAIL;
    public static int AVROOM_WARNING_VIDEO_PLAY_LAG;
    public static final String EVT_USERID = "EVT_USERID";
    public static final String EVT_ID = "EVT_ID";
    public static final String EVT_TIME = "EVT_TIME";
    public static final String EVT_DESCRIPTION = "EVT_MSG";
    public static final String NET_STATUS_USER_ID = "USER_ID";
    public static final String NET_STATUS_VIDEO_BITRATE = "VIDEO_BITRATE";
    public static final String NET_STATUS_AUDIO_BITRATE = "AUDIO_BITRATE";
    public static final String NET_STATUS_VIDEO_FPS = "VIDEO_FPS";
    public static final String NET_STATUS_NET_SPEED = "NET_SPEED";
    public static final String NET_STATUS_NET_JITTER = "NET_JITTER";
    public static final String NET_STATUS_CACHE_SIZE = "CACHE_SIZE";
    public static final String NET_STATUS_DROP_SIZE = "DROP_SIZE";
    public static final String NET_STATUS_VIDEO_WIDTH = "VIDEO_WIDTH";
    public static final String NET_STATUS_VIDEO_HEIGHT = "VIDEO_HEIGHT";
    public static final String NET_STATUS_CPU_USAGE = "CPU_USAGE";
    public static final String NET_STATUS_SERVER_IP = "SERVER_IP";
    public static final String NET_STATUS_CODEC_CACHE = "CODEC_CACHE";
    public static final String NET_STATUS_CODEC_DROP_CNT = "CODEC_DROP_CNT";
    public static final String NET_STATUS_SET_VIDEO_BITRATE = "SET_VIDEO_BITRATE";
    public static final String NET_STATUS_PLAYABLE_DURATION = "PLAYABLE_DURATION";
    public static int TXE_AUDIO_MODE_SPEAKER;
    public static int TXE_AUDIO_MODE_RECEIVER;
    public static int AVROOM_HOME_ORIENTATION_RIGHT;
    public static int AVROOM_HOME_ORIENTATION_DOWN;
    public static int AVROOM_HOME_ORIENTATION_LEFT;
    public static int AVROOM_HOME_ORIENTATION_UP;
    public static final int RENDER_MODE_FULL_FILL_SCREEN = 0;
    public static final int RENDER_MODE_ADJUST_RESOLUTION = 1;
    public static final int RENDER_ROTATION_PORTRAIT = 0;
    public static final int RENDER_ROTATION_LANDSCAPE = 270;
    public static int AVROOM_PUSH_PAUSETIME;
    public static int AVROOM_AUDIO_SAMPLE_RATE;
    public static float AVROOM_CACHETIME;
    public static float AVROOM_MIN_ADJUSTCACHETIME;
    public static float AVROOM_MAX_ADJUSTCACHETIME;
    public static int AVROOM_BITRATE;
    public static int AVROOM_MIN_BITRATE;
    public static int AVROOM_MAX_BITRATE;
    public static int AVROOM_QOS_INTERVAL;
    private static int[] sampleRateArray;
    
    public static void makeAACCodecSpecificData(final byte[] array, final int n, final int n2, final int n3) {
        int n4 = 0;
        for (int i = 0; i < TXCAVRoomConstants.sampleRateArray.length; ++i) {
            if (n2 == TXCAVRoomConstants.sampleRateArray[i]) {
                n4 = i;
            }
        }
        final short n5 = (short)((short)((short)((short)(0x0 | (n << 11 & 0xF800)) | (n4 << 7 & 0x780)) | (n3 << 3 & 0x78)) | 0x0);
        array[0] = (byte)(n5 >> 8 & 0xFF);
        array[1] = (byte)(n5 & 0xFF);
    }
    
    static {
        TXCAVRoomConstants.AVROOM_AUTH_BITS_DEFAULT = -1;
        TXCAVRoomConstants.AVROOM_AUTH_BITS_CREATE_ROOM = 1;
        TXCAVRoomConstants.AVROOM_AUTH_BITS_JOIN_ROOM = 2;
        TXCAVRoomConstants.AVROOM_AUTH_BITS_SEND_AUDIO = 4;
        TXCAVRoomConstants.AVROOM_AUTH_BITS_RECV_AUDIO = 8;
        TXCAVRoomConstants.AVROOM_AUTH_BITS_SEND_CAMERA_VIDEO = 16;
        TXCAVRoomConstants.AVROOM_AUTH_BITS_RECV_CAMERA_VIDEO = 32;
        TXCAVRoomConstants.AVROOM_AUTH_BITS_SEND_SCREEN_VIDEO = 64;
        TXCAVRoomConstants.AVROOM_AUTH_BITS_RECV_SCREEN_VIDEO = 128;
        TXCAVRoomConstants.AVROOM_EVT_REQUEST_IP_SUCC = 1001;
        TXCAVRoomConstants.AVROOM_EVT_CONNECT_SUCC = 1002;
        TXCAVRoomConstants.AVROOM_EVT_ENTER_ROOM_SUCC = 1003;
        TXCAVRoomConstants.AVROOM_EVT_EXIT_ROOM_SUCC = 1004;
        TXCAVRoomConstants.AVROOM_EVT_REQUEST_AVSEAT_SUCC = 1005;
        TXCAVRoomConstants.AVROOM_ERR_REQUEST_IP_FAIL = -1001;
        TXCAVRoomConstants.AVROOM_ERR_CONNECT_FAILE = -1002;
        TXCAVRoomConstants.AVROOM_ERR_ENTER_ROOM_FAIL = -1003;
        TXCAVRoomConstants.AVROOM_ERR_EXIT_ROOM_FAIL = -1004;
        TXCAVRoomConstants.AVROOM_ERR_REQUEST_AVSEAT_FAIL = -1005;
        TXCAVRoomConstants.AVROOM_WARNING_DISCONNECT = 2001;
        TXCAVRoomConstants.AVROOM_WARNING_RECONNECT = 2002;
        TXCAVRoomConstants.AVROOM_WARNING_NET_BUSY = 2003;
        TXCAVRoomConstants.AVROOM_EVT_OPEN_CAMERA_SUCC = 3001;
        TXCAVRoomConstants.AVROOM_EVT_START_VIDEO_ENCODER = 3002;
        TXCAVRoomConstants.AVROOM_EVT_UP_CHANGE_RESOLUTION = 3003;
        TXCAVRoomConstants.AVROOM_EVT_UP_CHANGE_BITRATE = 3004;
        TXCAVRoomConstants.AVROOM_EVT_FIRST_FRAME_AVAILABLE = 3005;
        TXCAVRoomConstants.AVROOM_WARNING_HW_ACCELERATION_ENCODE_FAIL = 3101;
        TXCAVRoomConstants.AVROOM_ERR_OPEN_CAMERA_FAIL = -3001;
        TXCAVRoomConstants.AVROOM_ERR_OPEN_MIC_FAIL = -3002;
        TXCAVRoomConstants.AVROOM_ERR_VIDEO_ENCODE_FAIL = -3003;
        TXCAVRoomConstants.AVROOM_ERR_AUDIO_ENCODE_FAIL = -3004;
        TXCAVRoomConstants.AVROOM_ERR_UNSUPPORTED_RESOLUTION = -3005;
        TXCAVRoomConstants.AVROOM_ERR_UNSUPPORTED_SAMPLERATE = -3006;
        TXCAVRoomConstants.AVROOM_EVT_RCV_FIRST_I_FRAME = 4001;
        TXCAVRoomConstants.AVROOM_EVT_PLAY_BEGIN = 4002;
        TXCAVRoomConstants.AVROOM_EVT_PLAY_LOADING = 4003;
        TXCAVRoomConstants.AVROOM_EVT_START_VIDEO_DECODER = 4004;
        TXCAVRoomConstants.AVROOM_EVT_DOWN_CHANGE_RESOLUTION = 4005;
        TXCAVRoomConstants.AVROOM_WARNING_VIDEO_DECODE_FAIL = 4101;
        TXCAVRoomConstants.AVROOM_WARNING_AUDIO_DECODE_FAIL = 4102;
        TXCAVRoomConstants.AVROOM_WARNING_HW_ACCELERATION_DECODE_FAIL = 4103;
        TXCAVRoomConstants.AVROOM_WARNING_VIDEO_PLAY_LAG = 4104;
        TXCAVRoomConstants.TXE_AUDIO_MODE_SPEAKER = 0;
        TXCAVRoomConstants.TXE_AUDIO_MODE_RECEIVER = 1;
        TXCAVRoomConstants.AVROOM_HOME_ORIENTATION_RIGHT = 0;
        TXCAVRoomConstants.AVROOM_HOME_ORIENTATION_DOWN = 1;
        TXCAVRoomConstants.AVROOM_HOME_ORIENTATION_LEFT = 2;
        TXCAVRoomConstants.AVROOM_HOME_ORIENTATION_UP = 3;
        TXCAVRoomConstants.AVROOM_PUSH_PAUSETIME = Integer.MAX_VALUE;
        TXCAVRoomConstants.AVROOM_AUDIO_SAMPLE_RATE = 16000;
        TXCAVRoomConstants.AVROOM_CACHETIME = AAAA.a;
        TXCAVRoomConstants.AVROOM_MIN_ADJUSTCACHETIME = AAAA.b;
        TXCAVRoomConstants.AVROOM_MAX_ADJUSTCACHETIME = AAAA.c;
        TXCAVRoomConstants.AVROOM_BITRATE = 400;
        TXCAVRoomConstants.AVROOM_MIN_BITRATE = 300;
        TXCAVRoomConstants.AVROOM_MAX_BITRATE = 600;
        TXCAVRoomConstants.AVROOM_QOS_INTERVAL = 2000;
        TXCAVRoomConstants.sampleRateArray = new int[] { 96000, 88200, 64000, 48000, 44100, 32000, 24000, 22050, 16000, 12000, 11025, 8000, 7350 };
    }
}
