package com.tencent.liteav.basic.datareport;

public class a
{
    public static String a;
    public static String b;
    public static String c;
    public static String d;
    public static String e;
    public static String f;
    public static String g;
    public static String h;
    public static String i;
    public static String j;
    public static String k;
    public static String l;
    public static String m;
    public static String n;
    public static String o;
    public static String p;
    public static String q;
    public static String r;
    public static String s;
    public static String t;
    public static String u;
    public static String v;
    public static String w;
    public static String x;
    public static String y;
    public static String z;
    public static String A;
    public static String B;
    public static String C;
    public static int D;
    public static int E;
    public static int F;
    public static int G;
    public static int H;
    public static int I;
    public static int J;
    public static int K;
    public static int L;
    public static int M;
    public static int N;
    public static int O;
    public static int P;
    public static int Q;
    public static int R;
    public static int S;
    public static int T;
    public static int U;
    public static int V;
    public static int W;
    public static int X;
    public static int Y;
    public static int Z;
    public static int aa;
    public static int ab;
    public static int ac;
    public static int ad;
    public static int ae;
    public static int af;
    public static int ag;
    public static int ah;
    public static int ai;
    public static int aj;
    public static int ak;
    public static int al;
    public static int am;
    public static int an;
    public static int ao;
    public static int ap;
    public static int aq;
    public static int ar;
    public static int as;
    public static int at;
    public static int au;
    public static int av;
    public static int aw;
    public static int ax;
    public static int ay;
    public static int az;
    public static int aA;
    public static int aB;
    public static int aC;
    public static int aD;
    public static int aE;
    public static int aF;
    public static int aG;
    public static int aH;
    public static int aI;
    public static int aJ;
    public static int aK;
    public static int aL;
    public static int aM;
    public static int aN;
    public static int aO;
    public static int aP;
    public static int aQ;
    public static int aR;
    public static int aS;
    public static int aT;
    public static int aU;
    public static int aV;
    public static int aW;
    public static int aX;
    public static int aY;
    public static int aZ;
    public static int ba;
    public static int bb;
    public static int bc;
    public static int bd;
    public static int be;
    public static int bf;
    public static int bg;
    public static int bh;
    public static int bi;
    public static int bj;
    public static int bk;
    public static int bl;
    public static int bm;
    public static int bn;
    public static int bo;
    public static int bp;
    public static int bq;
    public static int br;
    public static int bs;
    public static int bt;
    public static int bu;
    public static int bv;
    public static int bw;
    public static int bx;
    public static int by;
    public static int bz;
    public static int bA;
    public static int bB;
    public static int bC;
    public static int bD;
    public static int bE;
    public static int bF;
    public static int bG;
    public static int bH;
    public static int bI;
    
    static {
        com.tencent.liteav.basic.datareport.a.a = "u32_module_id";
        com.tencent.liteav.basic.datareport.a.b = "str_stream_url";
        com.tencent.liteav.basic.datareport.a.c = "platform";
        com.tencent.liteav.basic.datareport.a.d = "biz_id";
        com.tencent.liteav.basic.datareport.a.e = "app_id";
        com.tencent.liteav.basic.datareport.a.f = "dev_type";
        com.tencent.liteav.basic.datareport.a.g = "net_type";
        com.tencent.liteav.basic.datareport.a.h = "dev_id";
        com.tencent.liteav.basic.datareport.a.i = "dev_uuid";
        com.tencent.liteav.basic.datareport.a.j = "app_name";
        com.tencent.liteav.basic.datareport.a.k = "app_version";
        com.tencent.liteav.basic.datareport.a.l = "sys_version";
        com.tencent.liteav.basic.datareport.a.m = "mac_addr";
        com.tencent.liteav.basic.datareport.a.n = "evt_comm";
        com.tencent.liteav.basic.datareport.a.o = "event_id";
        com.tencent.liteav.basic.datareport.a.p = "err_code";
        com.tencent.liteav.basic.datareport.a.q = "err_info";
        com.tencent.liteav.basic.datareport.a.r = "ext";
        com.tencent.liteav.basic.datareport.a.s = "event_id";
        com.tencent.liteav.basic.datareport.a.t = "err_code";
        com.tencent.liteav.basic.datareport.a.u = "err_info";
        com.tencent.liteav.basic.datareport.a.v = "file_size";
        com.tencent.liteav.basic.datareport.a.w = "up_usetime";
        com.tencent.liteav.basic.datareport.a.x = "up_ip";
        com.tencent.liteav.basic.datareport.a.y = "ugc_upload";
        com.tencent.liteav.basic.datareport.a.z = "DAU";
        com.tencent.liteav.basic.datareport.a.A = "u32_error_code";
        com.tencent.liteav.basic.datareport.a.B = "str_error_msg";
        com.tencent.liteav.basic.datareport.a.C = "str_msg_more";
        com.tencent.liteav.basic.datareport.a.D = 1000;
        com.tencent.liteav.basic.datareport.a.E = 1001;
        com.tencent.liteav.basic.datareport.a.F = 1002;
        com.tencent.liteav.basic.datareport.a.G = 2001;
        com.tencent.liteav.basic.datareport.a.H = 2002;
        com.tencent.liteav.basic.datareport.a.I = 2003;
        com.tencent.liteav.basic.datareport.a.J = 2004;
        com.tencent.liteav.basic.datareport.a.K = 2005;
        com.tencent.liteav.basic.datareport.a.L = 2006;
        com.tencent.liteav.basic.datareport.a.M = 2007;
        com.tencent.liteav.basic.datareport.a.N = 2008;
        com.tencent.liteav.basic.datareport.a.O = 2009;
        com.tencent.liteav.basic.datareport.a.P = 40001;
        com.tencent.liteav.basic.datareport.a.Q = 40000;
        com.tencent.liteav.basic.datareport.a.R = 40002;
        com.tencent.liteav.basic.datareport.a.S = 40003;
        com.tencent.liteav.basic.datareport.a.T = 40005;
        com.tencent.liteav.basic.datareport.a.U = 40101;
        com.tencent.liteav.basic.datareport.a.V = 40100;
        com.tencent.liteav.basic.datareport.a.W = 40102;
        com.tencent.liteav.basic.datareport.a.X = 40501;
        com.tencent.liteav.basic.datareport.a.Y = 40500;
        com.tencent.liteav.basic.datareport.a.Z = 40502;
        com.tencent.liteav.basic.datareport.a.aa = 40201;
        com.tencent.liteav.basic.datareport.a.ab = 40200;
        com.tencent.liteav.basic.datareport.a.ac = 40202;
        com.tencent.liteav.basic.datareport.a.ad = 40301;
        com.tencent.liteav.basic.datareport.a.ae = 40401;
        com.tencent.liteav.basic.datareport.a.af = 40402;
        com.tencent.liteav.basic.datareport.a.ag = 49999;
        com.tencent.liteav.basic.datareport.a.ah = 1000;
        com.tencent.liteav.basic.datareport.a.ai = 1001;
        com.tencent.liteav.basic.datareport.a.aj = 1002;
        com.tencent.liteav.basic.datareport.a.ak = 1003;
        com.tencent.liteav.basic.datareport.a.al = 1004;
        com.tencent.liteav.basic.datareport.a.am = 1005;
        com.tencent.liteav.basic.datareport.a.an = 1006;
        com.tencent.liteav.basic.datareport.a.ao = 1007;
        com.tencent.liteav.basic.datareport.a.ap = 1008;
        com.tencent.liteav.basic.datareport.a.aq = 1009;
        com.tencent.liteav.basic.datareport.a.ar = 1010;
        com.tencent.liteav.basic.datareport.a.as = 1011;
        com.tencent.liteav.basic.datareport.a.at = 1001;
        com.tencent.liteav.basic.datareport.a.au = 1002;
        com.tencent.liteav.basic.datareport.a.av = 1003;
        com.tencent.liteav.basic.datareport.a.aw = 1004;
        com.tencent.liteav.basic.datareport.a.ax = 1005;
        com.tencent.liteav.basic.datareport.a.ay = 1006;
        com.tencent.liteav.basic.datareport.a.az = 1007;
        com.tencent.liteav.basic.datareport.a.aA = 1008;
        com.tencent.liteav.basic.datareport.a.aB = 1009;
        com.tencent.liteav.basic.datareport.a.aC = 1010;
        com.tencent.liteav.basic.datareport.a.aD = 1011;
        com.tencent.liteav.basic.datareport.a.aE = 1012;
        com.tencent.liteav.basic.datareport.a.aF = 1013;
        com.tencent.liteav.basic.datareport.a.aG = 1014;
        com.tencent.liteav.basic.datareport.a.aH = 1015;
        com.tencent.liteav.basic.datareport.a.aI = 1016;
        com.tencent.liteav.basic.datareport.a.aJ = 1017;
        com.tencent.liteav.basic.datareport.a.aK = 1018;
        com.tencent.liteav.basic.datareport.a.aL = 1019;
        com.tencent.liteav.basic.datareport.a.aM = 1020;
        com.tencent.liteav.basic.datareport.a.aN = 1021;
        com.tencent.liteav.basic.datareport.a.aO = 1022;
        com.tencent.liteav.basic.datareport.a.aP = 1023;
        com.tencent.liteav.basic.datareport.a.aQ = 1024;
        com.tencent.liteav.basic.datareport.a.aR = 1025;
        com.tencent.liteav.basic.datareport.a.aS = 1026;
        com.tencent.liteav.basic.datareport.a.aT = 1027;
        com.tencent.liteav.basic.datareport.a.aU = 1028;
        com.tencent.liteav.basic.datareport.a.aV = 1029;
        com.tencent.liteav.basic.datareport.a.aW = 1030;
        com.tencent.liteav.basic.datareport.a.aX = 1031;
        com.tencent.liteav.basic.datareport.a.aY = 1032;
        com.tencent.liteav.basic.datareport.a.aZ = 1033;
        com.tencent.liteav.basic.datareport.a.ba = 1034;
        com.tencent.liteav.basic.datareport.a.bb = 1041;
        com.tencent.liteav.basic.datareport.a.bc = 1042;
        com.tencent.liteav.basic.datareport.a.bd = 1043;
        com.tencent.liteav.basic.datareport.a.be = 1044;
        com.tencent.liteav.basic.datareport.a.bf = 1045;
        com.tencent.liteav.basic.datareport.a.bg = 1046;
        com.tencent.liteav.basic.datareport.a.bh = 1047;
        com.tencent.liteav.basic.datareport.a.bi = 1048;
        com.tencent.liteav.basic.datareport.a.bj = 1049;
        com.tencent.liteav.basic.datareport.a.bk = 1050;
        com.tencent.liteav.basic.datareport.a.bl = 1051;
        com.tencent.liteav.basic.datareport.a.bm = 1052;
        com.tencent.liteav.basic.datareport.a.bn = 1053;
        com.tencent.liteav.basic.datareport.a.bo = 1054;
        com.tencent.liteav.basic.datareport.a.bp = 1055;
        com.tencent.liteav.basic.datareport.a.bq = 1056;
        com.tencent.liteav.basic.datareport.a.br = 1099;
        com.tencent.liteav.basic.datareport.a.bs = 1997;
        com.tencent.liteav.basic.datareport.a.bt = 1998;
        com.tencent.liteav.basic.datareport.a.bu = 1999;
        com.tencent.liteav.basic.datareport.a.bv = 1301;
        com.tencent.liteav.basic.datareport.a.bw = 1501;
        com.tencent.liteav.basic.datareport.a.bx = 1502;
        com.tencent.liteav.basic.datareport.a.by = 1551;
        com.tencent.liteav.basic.datareport.a.bz = 1552;
        com.tencent.liteav.basic.datareport.a.bA = 1553;
        com.tencent.liteav.basic.datareport.a.bB = 1554;
        com.tencent.liteav.basic.datareport.a.bC = 1555;
        com.tencent.liteav.basic.datareport.a.bD = 1556;
        com.tencent.liteav.basic.datareport.a.bE = 1557;
        com.tencent.liteav.basic.datareport.a.bF = 1;
        com.tencent.liteav.basic.datareport.a.bG = 1;
        com.tencent.liteav.basic.datareport.a.bH = 2;
        com.tencent.liteav.basic.datareport.a.bI = 3;
    }
}
